- id: retropie_shutdown
  alias: RetroPie powering down
  trigger:
    platform: mqtt
    topic: "stat/retropie/POWER"
    payload: 'off'
  action:
    - service: script.retropie_power_off
- id: retropie_startup
  alias: RetroPie boots up
  trigger:
    - platform: mqtt
      topic: "stat/retropie/POWER"
      payload: 'on'
    - platform: template
      value_template: "{{ is_state_attr('media_player.receiver', 'source', 'RetroPie') }}"
  action:
    - service: script.retropie_power_on


- id: alarm_on_at_night
  alias: Turn alarm on at night
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel
