- id: power_cycle_onkyo
  alias: Power Cycle Onkyo Receiver nightly
  trigger:
    platform: time
    at: '4:00:00'
  action:
    - service: script.power_cycle_onkyo


- id: retropie_shutdown
  alias: RetroPie powering down
  trigger:
    platform: mqtt
    topic: "stat/retropie/POWER"
    payload: 'off'
  action:
    - service: script.retropie_power_off
- id: retropie_startup
  alias: RetroPie boots up
  trigger:
    - platform: mqtt
      topic: "stat/retropie/POWER"
      payload: 'on'
    - platform: template
      value_template: "{{ is_state_attr('media_player.receiver', 'source', 'RetroPie') }}"
  action:
    - service: script.retropie_power_on

- id: lights_on_at_sunset
  alias: Lights on at Sunset
  trigger:
    - platform: sun
      event: sunset
  condition:
      - condition: time
        before: '22:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.rock_lamp
          - light.guest_room_christmas_lights
          - light.christmas_tree

- id: lights_off
  alias: Lights Off
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: '22:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.rock_lamp
          - light.guest_room_christmas_lights
          - light.christmas_tree

- id: alarm_on_at_night
  alias: Turn alarm on at night
  trigger:
    platform: time
    at: '22:00:00'
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel
