- id: retropie_shutdown
  alias: RetroPie powering down
  trigger:
    platform: mqtt
    topic: "stat/retropie/POWER"
    payload: 'off'
  action:
    - service: script.retropie_power_off
- id: retropie_startup
  alias: RetroPie boots up
  trigger:
    - platform: mqtt
      topic: "stat/retropie/POWER"
      payload: 'on'
    - platform: template
      value_template: "{{ is_state_attr('media_player.receiver', 'source', 'RetroPie') }}"
  action:
    - service: script.retropie_power_on

- id: office_lamp_on
  alias: Office Lights On
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:45:00'
  condition:
      - condition: time
        before: '19:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_lamp

- id: office_lamp_off
  alias: Office Lights Off
  trigger:
    - platform: time
      at: '19:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.office_lamp

- id: lights_on_at_sunset
  alias: Lights on at Sunset
  trigger:
    - platform: sun
      event: sunset
  condition:
      - condition: time
        before: !secret constants_bed_time
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.rock_lamp

- id: lights_off
  alias: Lights Off
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: !secret constants_bed_time
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.rock_lamp

- id: alarm_on_at_night
  alias: Turn alarm on at night
  trigger:
    platform: time
    at: !secret constants_bed_time
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel

- id: arlo_on_with_alarm
  alias: Turn Arlo on with the alarm
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_panel
      to: armed_home
    - platform: state
      entity_id: alarm_control_panel.alarm_panel
      to: armed_away
  action:
    service: alarm_control_panel.alarm_arm_home
    entity_id: alarm_control_panel.hercules

- id: arlo_off_with_alarm
  alias: Turn Arlo off with the alarm
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_panel
      to: disarmed
  action:
    service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.hercules

- id: hot_tub_lights_off
  alias: Turn off Hot Tub Lights with Rock Lamp
  trigger:
    - platform: state
      entity_id: light.rock_lamp
      to: 'off'
  action:
    service: light.turn_off
    entity_id: light.hot_tub_lights

- id: hot_tub_lights_on
  alias: Turn on Hot Tub Lights with Rock Lamp
  trigger:
    - platform: state
      entity_id: light.rock_lamp
      to: 'on'
  action:
    service: light.turn_on
    entity_id: light.hot_tub_lights

- id: sync_tv_and_retropi_power_with_receiver
  alias: Sync TV & RetroPi power with receiver
  trigger:
    platform: state
    entity_id: media_player.receiver
    to: 'off'
  action:
    - service: shell_command.retropi_power_off
    - service: switch.turn_off
      data:
        entity_id: switch.tv

- id: notify_when_alarm_triggered
  alias: Notify when alarm is triggered
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_panel
      to: triggered
  action:
    - service: notify.ios_matthews_iphone
      data:
        message: "Alarm Triggered!"
        data:
          push:
            category: alarm

- id: ios_triggered_disable_alarm
  alias: iOS Triggered - Disable Alarm
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SILENCE_ALARM
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel

- id: matt_arrives_home
  alias: Matt Arrives Home
  trigger:
    - platform: state
      entity_id: device_tracker.matthews_iphone
      to: home
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel
    - service: notify.ios_matthews_iphone
      data:
        message: "Matt arrived home"
        data:
          push:
            category: "GARAGE"

- id: matt_leaves_home
  alias: Matt Leaves Home
  trigger:
    - entity_id: device_tracker.matthews_iphone
      platform: state
      to: not_home
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel

- id: ios_triggered_open_garage
  alias: iOS Triggered - Open Garage
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: OPEN_GARAGE
  action:
    - service: cover.open_cover
      entity_id: cover.garage_door

- id: flash_rock_lamp_on_donwload_complete
  alias: Flash Rock Lamp on download complete
  trigger:
    - platform: state
      entity_id: sensor.sabnzbd_status
      from: Downloading
      to: Idle
  action:
    - service: script.flash_rock_lamp
