- id: office_lamp_on
  alias: Office Lights On
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:45:00'
  condition:
      - condition: time
        before: '19:00:00'
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.office_lamp

- id: office_lamp_off
  alias: Office Lights Off
  trigger:
    - platform: time
      at: '19:00:00'
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.office_lamp

- id: lights_on_at_sunset
  alias: Lights on at Sunset
  trigger:
    - platform: sun
      event: sunset
  condition:
      - condition: time
        before: !secret constants_bed_time
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.rock_lamp

- id: lights_off
  alias: Lights Off
  trigger:
    - platform: homeassistant
      event: start
    - platform: time
      at: !secret constants_bed_time
  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.rock_lamp

- id: alarm_on_at_night
  alias: Turn alarm on at night
  trigger:
    platform: time
    at: !secret constants_bed_time
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel

- id: notify_when_alarm_triggered
  alias: Notify when alarm is triggered
  trigger:
    - platform: state
      entity_id: alarm_control_panel.alarm_panel
      to: triggered
  action:
    - service: notify.ios_matthews_iphone
      data:
        message: "Alarm Triggered!"
        data:
          push:
            category: alarm

- id: ios_triggered_disable_alarm
  alias: iOS Triggered - Disable Alarm
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: SILENCE_ALARM
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel

- id: matt_arrives_home
  alias: Matt Arrives Home
  trigger:
    - platform: state
      entity_id: device_tracker.matthews_iphone
      to: home
  action:
    - service: alarm_control_panel.alarm_disarm
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel
    - service: notify.ios_matthews_iphone
      data:
        message: "Matt arrived home"
        data:
          push:
            category: "GARAGE"

- id: matt_leaves_home
  alias: Matt Leaves Home
  trigger:
    - entity_id: device_tracker.matthews_iphone
      platform: state
      to: not_home
  action:
    - service: alarm_control_panel.alarm_arm_home
      data:
        code: !secret alarm_master_code
        entity_id: alarm_control_panel.alarm_panel

- id: ios_triggered_open_garage
  alias: iOS Triggered - Open Garage
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: OPEN_GARAGE
  action:
    - service: cover.open_cover
      entity_id: cover.garage_door
