#!/bin/bash

VERSION="`cat .HA_VERSION`"

time docker run \
  --rm \
  -v $PWD:/root/.homeassistant/ \
  -v $PWD/check-assets/ssl:/ssl \
  -w /root/.homeassistant/ \
  homeassistant/amd64-homeassistant:$VERSION \
  hass --script check_config
