alarm_control_panel:
  - platform: arlo
    away_mode_name: Armed

alarmdecoder:
  device:
    type: socket
    host: 192.168.3.27
    port: 10000
  panel_display: On
  zones:
    #8:
    #  name: Alarm Box
    #  type: opening
    #9:
    #  name: Service Equipment
    #  type: ????
    10:
      name: Garage Door
      type: opening
    11:
      name: Front Door
      type: opening
    12:
      name: Family Slider
      type: opening
    13:
      name: Left Living Room Window
      type: opening
    14:
      name: Right Living Room Window
      type: opening
    15:
      name: Upstairs Motion
      type: motion
    16:
      name: Guest Room Window
      type: opening
    #17:
    #  name: Stairway Smoke
    #  type: smoke
    18:
      name: Bathroom Window
      type: opening
    19:
      name: Office Window
      type: opening
    20:
      name: Master Bedroom Window
      type: opening

apcupsd:
  host: a722577e-apcupsd

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

binary_sensor:
  - platform: command_line
    command: "curl -s -N --connect-timeout 1 http://192.168.3.42:8060/query/device-info | sed -ne 's/.*<power-mode>\\(.*\\)<\\/power-mode>.*/\\1/p' || echo -n DisplayOff"
    device_class: light
    name: TV
    payload_on: PowerOn
    payload_off: DisplayOff

camera:
  - platform: arlo

# Enables configuration UI
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

cover:
  - platform: mqtt
    command_topic: "home-assistant/cover/set"
    name: "Garage Door"
    state_topic: "home-assistant/cover"

# Discover some devices automatically
discovery:

# Enables the frontend
frontend:
  javascript_version: latest

# Enables support for tracking state changes over time
history:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages/

homekit:
  entity_config:
    alarm_control_panel.alarm_panel:
      code: !secret alarm_master_code
  filter:
    exclude_domains:
      - device_tracker
      - script
    exclude_entities:
      - binary_sensor.bathroom_window
      - binary_sensor.downstairs_thermostat_fan
      - binary_sensor.downstairs_thermostat_has_leaf
      - binary_sensor.downstairs_thermostat_is_locked
      - binary_sensor.downstairs_thermostat_is_using_emergency_heat
      - binary_sensor.downstairs_thermostat_online
      - binary_sensor.family_slider
      - binary_sensor.front_door
      - binary_sensor.garage_door
      - binary_sensor.guest_room_window
      - binary_sensor.left_living_room_window
      - binary_sensor.master_bedroom_window
      - binary_sensor.office_window
      - binary_sensor.right_living_room_window
      - binary_sensor.tv
      - binary_sensor.tv
      - binary_sensor.upstairs_motion
      - binary_sensor.upstairs_motion
      - sensor.battery_level_drive
      - sensor.battery_level_yard
      - sensor.downstairs_thermostat_target
      - sensor.lesley_paiges_iphone_battery_level
      - sensor.matthews_iphone_battery_level
      - sensor.mi_flora_battery
      - sensor.mi_flora_conductivity
      - sensor.mi_flora_light_intensity
      - sensor.mi_flora_moisture
      - sensor.mi_flora_temperature
      - sensor.ups_battery
      - sensor.ups_load
      - switch.tv
      - switch.tv_wakeonlan

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5
  server_port: 443
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

ios:
  push:
    categories:
      - name: Alarm
        identifier: alarm
        actions:
          - identifier: 'SILENCE_ALARM'
            authenticationRequired: true
            destructive: true
            title: 'Silence Alarm'
          - identifier: 'DO_NOTHING'
            title: 'Do Nothing'
      - name: Garage
        identifier: 'GARAGE'
        actions:
          - identifier: 'OPEN_GARAGE'
            authenticationRequired: true
            destructive: true
            title: 'Open Garage'
          - identifier: 'DO_NOTHING'
            title: 'Do nothing'

light:
  - platform: mqtt
    command_topic: "cmnd/rock-lamp/POWER"
    name: Rock Lamp
    payload_off: "OFF"
    payload_on: "ON"
    qos: 1
    retain: true
    state_topic: "stat/rock-lamp/POWER"

  - platform: mqtt
    command_topic: "cmnd/hot-tub/POWER"
    name: Hot Tub Lights
    payload_off: "OFF"
    payload_on: "ON"
    qos: 1
    retain: true
    state_topic: "stat/hot-tub/POWER"

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

mqtt:
  broker: !secret mqtt_broker
  discovery: true
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  structure:
    - !secret nest_structure_1

openuv:
  api_key: !secret openuv_api_key

panel_iframe:
  pihole:
    title: Pi-hole
    icon: mdi:block-helper
    url: !secret pihole_url
  sonweb:
    title: SonWEB
    icon: mdi:lightbulb-on
    url: !secret sonweb_url

recorder:
  db_url: !secret recorder_db_url
  exclude:
    entities:
      - sensor.alarm_panel_display
      - sun.sun

sabnzbd:
  host: !secret sabnzbd_host
  api_key: !secret sabnzbd_api_key
  sensors:
    - current_status
    - speed
    - queue_size
    - queue_remaining
    - disk_size
    - disk_free
    - queue_count
    - day_size
    - week_size
    - month_size
    - total_size

sensor:
  - platform: apcupsd
    resources:
      - bcharge
      - linev
      - loadpct
      - nominv
      - nompower
      - numxfers
      - status
      - timeleft
      - tonbatt

  - platform: arlo

  - platform: miflora
    mac: 'C4:7C:8D:66:5D:E7'

  - platform: mqtt
    state_topic: "tele/hot-tub/SENSOR"
    name: "Hot Tub"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.DS18B20.Temperature }}'

  - platform: pi_hole
    host: !secret pihole_host
    ssl: true
    verify_ssl: false

  - platform: radarr
    host: !secret radarr_host
    api_key: !secret radarr_api_key
    monitored_conditions:
      - movies
      - upcoming
      - commands
      - diskspace
      - status

  - platform: sonarr
    host: !secret sonarr_host
    api_key: !secret sonarr_api_key
    monitored_conditions:
      - series
      - upcoming
      - wanted
      - queue
      - commands
      - diskspace

  - platform: speedtest
    minute:
      - 0
      - 10
      - 20
      - 30
      - 40
      - 50
    monitored_conditions:
      - ping

  - platform: template
    sensors:
      kitchen_smoke_and_co_detector_battery_level:
        value_template: '{{states.zwave.kitchen_smoke_and_co_detector.attributes.battery_level}}'
        friendly_name: 'Kitchen Smoke/CO Alarm Battery'
        unit_of_measurement: '%'
      upstairs_smoke_and_co_detector_battery_level:
        value_template: '{{states.zwave.upstairs_smoke_and_co_detector.attributes.battery_level}}'
        friendly_name: 'Upstairs Smoke/CO Alarm Battery'
        unit_of_measurement: '%'

  - platform: yweather
    monitored_conditions:
      - temperature
    name: "Current Outside"
    woeid: 12797392

  - platform: yr

shell_command:
  retropi_power_off: ssh pi@192.168.3.28 'sudo shutdown -h now'
  tv_power_off: curl -X POST http://192.168.3.42:8060/keypress/PowerOff
  tv_power_on: curl -X POST http://192.168.3.42:8060/keypress/PowerOn

# Track the sun
sun:

switch:
  - platform: template
    switches:
      tv:
        friendly_name: TV
        value_template: "{{ is_state('binary_sensor.tv', 'on') }}"
        turn_on:
          service: script.tv_power_on
        turn_off:
          service: shell_command.tv_power_off

  - platform: wake_on_lan
    mac_address: 0c:62:a6:50:d4:80
    name: TV Wake-on-LAN
    host: "192.168.3.42"

  - platform: mqtt
    command_topic: "cmnd/retropie-power/POWER"
    name: RetroPie Power
    payload_off: "OFF"
    payload_on: "ON"
    qos: 1
    retain: true
    state_topic: "stat/retropie-power/POWER"

tradfri:
  host: 192.168.3.44

# Text to speech
tts:
  - platform: google

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

vacuum:
  - platform: roomba
    host: !secret roomba_host
    username: !secret roomba_username
    password: !secret roomba_password

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

zwave:
  usb_path: /dev/ttyACM0
