alarm_control_panel:
  - platform: arlo
    away_mode_name: Armed

alarmdecoder:
  device:
    type: socket
    host: 192.168.1.27
    port: 10000
  panel_display: On
  zones:
    #8:
    #  name: Alarm Box
    #  type: opening
    #9:
    #  name: Service Equipment
    #  type: ????
    10:
      name: Garage Door
      type: opening
    11:
      name: Front Door
      type: opening
    12:
      name: Family Slider
      type: opening
    13:
      name: Left Living Room Window
      type: opening
    14:
      name: Right Living Room Window
      type: opening
    15:
      name: Upstairs Motion
      type: motion
    16:
      name: Guest Room Window
      type: opening
    #17:
    #  name: Stairway Smoke
    #  type: smoke
    18:
      name: Bathroom Window
      type: opening
    19:
      name: Office Window
      type: opening
    20:
      name: Master Bedroom Window
      type: opening

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

camera:
  - platform: arlo

# Enables configuration UI
config:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

cover:
  - platform: mqtt
    command_topic: "home-assistant/cover/set"
    name: "Garage Door"
    state_topic: "home-assistant/cover"

# Discover some devices automatically
discovery:

fan:
  - platform: mqtt
    command_topic: "cmnd/bedroom-fan/POWER"
    name: Bedroom Fan
    speeds:
      - off
      - high
    state_topic: "stat/bedroom-fan/POWER"

# Enables the frontend
frontend:

# Enables support for tracking state changes over time
history:

homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret homeassistant_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

homekit:
  entity_config:
    alarm_control_panel.alarm_panel:
      code: !secret alarm_master_code

http:
  api_password: !secret http_api_password
  base_url: !secret http_base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

light:
  - platform: mqtt
    command_topic: "cmnd/rock-lamp/POWER"
    name: Rock Lamp
    state_topic: "stat/rock-lamp/POWER"

  - platform: mqtt
    command_topic: "cmnd/office-lamp/POWER"
    name: Office Lamp
    state_topic: "stat/office-lamp/POWER"

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

media_player:
  - platform: onkyo
    host: 192.168.1.24
    name: Receiver
    sources:
      dvd: Apple TV
      video2: Roku
      video3: RetroPie
      video4: AUX
      #video1: STB/DVR
      #video6: PC
      #phono: PHONO
      #cd: DOCK
      #fm: fm
      #am: am
      #usb: usb
      #network: network

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret
  structure:
    - !secret nest_structure_1

recorder:
  db_url: !secret recorder_db_url

# Weather prediction
sensor:
  - platform: arlo

  - platform: mqtt
    state_topic: "tele/bedroom-fan/SENSOR"
    name: "Bedroom Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.AM2301.Humidity }}'

  - platform: mqtt
    state_topic: "tele/bedroom-fan/SENSOR"
    name: "Bedroom Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.AM2301.Temperature }}'

  - platform: mqtt
    state_topic: "tele/hot-tub/SENSOR"
    name: "Hot Tub"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.DS18B20.Temperature }}'

  - platform: yweather
    monitored_conditions:
      - temperature
    name: "Current Outside"
    woeid: 12797392

  - platform: yr

# Track the sun
sun:

switch:
  - platform: mqtt
    command_topic: "cmnd/onkyo-power/POWER"
    name: Onkyo Power
    payload_off: "OFF"
    payload_on: "ON"
    qos: 1
    retain: true
    state_topic: "stat/onkyo-power/POWER"

  - platform: mqtt
    command_topic: "cmnd/retropie-power/POWER"
    name: RetroPie Power
    payload_off: "OFF"
    payload_on: "ON"
    qos: 1
    retain: true
    state_topic: "stat/retropie-power/POWER"

# Text to speech
tts:
  - platform: google

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

vacuum:
  - platform: roomba
    host: !secret roomba_host
    username: !secret roomba_username
    password: !secret roomba_password

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
