##############################################################################
# Automations for handling Scene select buttons on page 1

automation:
  # Set font and text labels for scene buttons on device connection
  - alias: hasp_bedroom_p1_ScenesInit
    trigger:
    - platform: state
      entity_id: 'alarm_control_panel.alarm_panel'
    - platform: state
      entity_id: 'binary_sensor.bedroom_connected'
      to: 'on'
    - platform: state
      entity_id: 'light.hot_tub'
    - platform: homeassistant
      event: start
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom/command/p[1].b[4].font'
        payload: '1'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom/command/p[1].b[4].txt'
        payload_template: '"Alarm {{ states("alarm_control_panel.alarm_panel").split("_")[0] | title }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom/command/p[1].b[5].font'
        payload: '0'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom/command/p[1].b[5].txt'
        payload_template: '"Hot Tub Lights {{ states("light.hot_tub") | title }}"'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom/command/p[1].b[6].font'
        payload: '2'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom/command/p[1].b[6].txt'
        payload: '""'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom/command/p[1].b[7].font'
        payload: '2'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom/command/p[1].b[7].txt'
        payload: '""'

  # Toggle alarm when p[1].b[4] pressed
  - alias: hasp_bedroom_p1_SceneButton4_1
    trigger:
    - platform: mqtt
      topic: 'hasp/bedroom/state/p[1].b[4]'
      payload: 'ON'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'alarm_control_panel.alarm_panel'
          state: 'armed_home'
        - condition: state
          entity_id: 'alarm_control_panel.alarm_panel'
          state: 'armed_away'
        - condition: state
          entity_id: 'alarm_control_panel.alarm_panel'
          state: 'triggered'
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          code: !secret alarm_master_code
          entity_id: alarm_control_panel.alarm_panel

  - alias: hasp_bedroom_p1_SceneButton4_2
    trigger:
    - platform: mqtt
      topic: 'hasp/bedroom/state/p[1].b[4]'
      payload: 'ON'
    condition:
      - condition: state
        entity_id: 'alarm_control_panel.alarm_panel'
        state: 'disarmed'
    action:
      - service: alarm_control_panel.alarm_arm_home
        data:
          code: !secret alarm_master_code
          entity_id: alarm_control_panel.alarm_panel

  # Toggle Hot tub lights when p[1].b[5] pressed
  - alias: hasp_bedroom_p1_SceneButton5
    trigger:
    - platform: mqtt
      topic: 'hasp/bedroom/state/p[1].b[5]'
      payload: 'ON'
    action:
    - service: light.toggle
      entity_id: light.hot_tub
