alarm_master_code: 1234

homeassistant_elevation: 6430
homeassistant_latitude: 36.5109
homeassistant_longitude: -104.914

http_api_password: password
http_base_url: home-assistant.duckdns.org

mqtt_broker: 192.168.1.1
mqtt_username: username
mqtt_password: password

nest_client_id: client_id
nest_client_secret: client_secret

recorder_db_url: mysql://username:password@hostname/dbname
