alarm_master_code: 1234

arlo_password: password
arlo_username: username

constants_bed_time: '00:00:00'

homeassistant_elevation: 6430
homeassistant_latitude: 36.5109
homeassistant_longitude: -104.914

homekit_pincode: '123-45-678'

http_api_password: password
http_base_url: home-assistant.duckdns.org

mqtt_broker: 192.168.1.1
mqtt_username: username
mqtt_password: password

nest_client_id: client_id
nest_client_secret: client_secret
nest_structure_1: some address

recorder_db_url: mysql://username:password@hostname/dbname

roomba_host: 192.168.1.1
roomba_username: username
roomba_password: password
