##############################################################################
# Automations and required components to configure colors on the HASP panel
#
# Check out this site for easy color code selection and conversion:
# https://nodtem66.github.io/nextion-hmi-color-convert/index.html

input_number:
  hasp_bedroom_plate_selectedforegroundcolor:
    name: bedroom_plate Selected Foreground Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_bedroom_plate_selectedbackgroundcolor:
    name: bedroom_plate Selected Background Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_bedroom_plate_unselectedforegroundcolor:
    name: bedroom_plate Unselected Foreground Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
  hasp_bedroom_plate_unselectedbackgroundcolor:
    name: bedroom_plate Unselected Background Color
    icon: mdi:palette
    min: 0
    max: 65535
    step: 1
    mode: box
group:
  bedroom_plate_colors:
    name: bedroom_plate Colors
    view: no
    entities:
      - input_number.hasp_bedroom_plate_selectedforegroundcolor
      - input_number.hasp_bedroom_plate_selectedbackgroundcolor
      - input_number.hasp_bedroom_plate_unselectedforegroundcolor
      - input_number.hasp_bedroom_plate_unselectedbackgroundcolor
