# If you've installed and configured a motion sensor in the HASP device, copy
# this file to packages/bedroom_plate

binary_sensor:
  - platform: mqtt
    name: bedroom_plate Motion Sensor
    device_class: motion
    state_topic: "hasp/bedroom_plate/motion/state"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "hasp/bedroom_plate/status"
    payload_available: "ON"
    payload_not_available: "OFF"

# Use the motion sensor to switch between pages configured for buttons 1 and 2.
# Use case: Page button 1 has interactive controls, page button 2 has information
# Interaction:
# - When user isn't nearby, display shows information like a clock or weather on page 2.
# - When a person approachs, switch to interactive controls like the scene buttons on page 1.
automation:
  - alias: hasp_bedroom_plate_00_MotionSelectPageButton1
    trigger:
    - platform: state
      entity_id: 'binary_sensor.bedroom_plate_motion_sensor'
      to: 'on'
    condition:
    - condition: state
      entity_id: 'binary_sensor.bedroom_plate_connected'
      state: 'on'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_bedroom_plate_activepage'
        value: '{{states.input_number.hasp_bedroom_plate_pagebutton1page.state|int}}'

  - alias: hasp_bedroom_plate_00_NoMotionSelectPageButton2
    trigger:
    - platform: state
      entity_id: 'binary_sensor.bedroom_plate_motion_sensor'
      to: 'off'
    condition:
    - condition: state
      entity_id: 'binary_sensor.bedroom_plate_connected'
      state: 'on'
    action:
    - service: input_number.set_value
      data_template:
        entity_id: 'input_number.hasp_bedroom_plate_activepage'
        value: '{{states.input_number.hasp_bedroom_plate_pagebutton2page.state|int}}'
