##############################################################################
# Automations to set colors on HASP Page 6

automation:
  - alias: hasp_bedroom_plate_p6_ColorConfig
    trigger:
    - platform: state
      entity_id: 'binary_sensor.bedroom_plate_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_bedroom_plate_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bedroom_plate_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_bedroom_plate_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_bedroom_plate_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom_plate/command/json'
        payload_template: >-
          [{%- for i in range(4,12) -%}"p[6].b[{{i}}].pco={{ states.input_number.hasp_bedroom_plate_selectedforegroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(4,12) -%}"p[6].b[{{i}}].bco={{ states.input_number.hasp_bedroom_plate_selectedbackgroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(4,12) -%}"p[6].b[{{i}}].pco2={{ states.input_number.hasp_bedroom_plate_unselectedforegroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(4,12) -%}"p[6].b[{{i}}].bco2={{ states.input_number.hasp_bedroom_plate_unselectedbackgroundcolor.state|int }}",{%- endfor -%}]
