##############################################################################
# The devices created below are essential to the page control automations
# and you'll probably want to carry them over to your own configuration
homeassistant:
  customize:
    input_number.hasp_bedroom_plate_alarmcode1:
      hidden: true
    input_number.hasp_bedroom_plate_alarmcode2:
      hidden: true
    input_number.hasp_bedroom_plate_alarmcode3:
      hidden: true
    input_number.hasp_bedroom_plate_alarmcode4:
      hidden: true

# Enable this iframe to integrate the HASP web admin panel in Hass.
# This will not work if you have SSL enabled, see details here:
# https://www.home-assistant.io/components/panel_iframe/
#
panel_iframe:
  bedroom_plate:
    title: "bedroom_plate"
    url: "http://bedroom_plate"
    icon: "mdi:cellphone-text"

light:
  - platform: mqtt
    name: bedroom_plate Backlight
    command_topic: "hasp/bedroom_plate/light/switch"
    state_topic: "hasp/bedroom_plate/light/state"
    brightness_state_topic: "hasp/bedroom_plate/brightness/state"
    brightness_command_topic: "hasp/bedroom_plate/brightness/set"
    availability_topic: "hasp/bedroom_plate/status"
    payload_available: "ON"
    payload_not_available: "OFF"

binary_sensor:
  - platform: mqtt
    name: bedroom_plate Connected
    device_class: connectivity
    state_topic: "hasp/bedroom_plate/status"
    payload_on: "ON"
    payload_off: "OFF"
    availability_topic: "hasp/bedroom_plate/status"
    payload_available: "ON"
    payload_not_available: "OFF"

sensor:
  - platform: mqtt
    name: bedroom_plate Sensor
    state_topic: "hasp/bedroom_plate/sensor"
    value_template: '{{ value_json.status }}'
    json_attributes:
      - espVersion
      - updateESPAvailable
      - lcdVersion
      - updateLcdAvailable
      - espUptime
      - signalStrength
      - haspIP

input_text:
  hasp_bedroom_plate_pagebutton1label:
    name: bedroom_plate Page 1 Label
    icon: mdi:book-open-page-variant
  hasp_bedroom_plate_pagebutton2label:
    name: bedroom_plate Page 2 Label
    icon: mdi:book-open-page-variant
  hasp_bedroom_plate_pagebutton3label:
    name: bedroom_plate Page 3 Label
    icon: mdi:book-open-page-variant

input_number:
  hasp_bedroom_plate_pagebutton1page:
    name: bedroom_plate Page 1 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_bedroom_plate_pagebutton2page:
    name: bedroom_plate Page 2 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_bedroom_plate_pagebutton3page:
    name: bedroom_plate Page 3 Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_bedroom_plate_activepage:
    name: bedroom_plate Active Page
    icon: mdi:format-list-numbers
    min: 0
    max: 9
    step: 1
  hasp_bedroom_plate_alarmcode1:
    name: bedroom_plate AlarmCode1
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_bedroom_plate_alarmcode2:
    name: bedroom_plate AlarmCode2
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_bedroom_plate_alarmcode3:
    name: bedroom_plate AlarmCode3
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1
  hasp_bedroom_plate_alarmcode4:
    name: bedroom_plate AlarmCode4
    icon: mdi:format-list-numbers
    min: -1
    max: 9
    step: 1
    initial: -1

group:
  bedroom_plate:
    name: bedroom_plate
    view: yes
    entities:
      - binary_sensor.bedroom_plate_connected
      - sensor.bedroom_plate_sensor
      - light.bedroom_plate_backlight
      - group.bedroom_plate_pageselect
      - group.bedroom_plate_colors
      - group.bedroom_plate_automations
      - group.bedroom_plate_fake_lights
  bedroom_plate_fake_lights:
    name: bedroom_plate Fake Lights
    view: no
    entities:
      - light.light_1
      - light.light_2
      - light.light_3
  bedroom_plate_pageselect:
    name: bedroom_plate Page Selection
    view: no
    entities:
      - input_number.hasp_bedroom_plate_activepage
      - input_number.hasp_bedroom_plate_pagebutton1page
      - input_text.hasp_bedroom_plate_pagebutton1label
      - input_number.hasp_bedroom_plate_pagebutton2page
      - input_text.hasp_bedroom_plate_pagebutton2label
      - input_number.hasp_bedroom_plate_pagebutton3page
      - input_text.hasp_bedroom_plate_pagebutton3label
  bedroom_plate_automations:
    name: bedroom_plate automations
    view: no
    entities:
      - automation.hasp_bedroom_plate_00_firsttimesetup

automation:
##############################################################################
# Run first time setup commands
  - alias: hasp_bedroom_plate_00_FirstTimeSetup
    trigger: []
    action:
      - service: automation.trigger
        data:
          entity_id: 'automation.hasp_bedroom_plate_00_automationgroupupdate'
      - service: homeassistant.turn_on
        data:
          entity_id: 'group.bedroom_plate_automations'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_bedroom_plate_pagebutton1label'
          value: 'scenes'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_bedroom_plate_pagebutton2label'
          value: 'status'
      - service: input_text.set_value
        data:
          entity_id: 'input_text.hasp_bedroom_plate_pagebutton3label'
          value: 'lights'
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_bedroom_plate_pagebutton1page'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_bedroom_plate_pagebutton2page'
          value: 2
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_bedroom_plate_pagebutton3page'
          value: 3
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_bedroom_plate_activepage'
          value: 1
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_bedroom_plate_selectedforegroundcolor'
          value: 0
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_bedroom_plate_selectedbackgroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_bedroom_plate_unselectedforegroundcolor'
          value: 65535
      - service: input_number.set_value
        data:
          entity_id: 'input_number.hasp_bedroom_plate_unselectedbackgroundcolor'
          value: 25388

##############################################################################
# Set automation group members on start - Thanks @Nightcat!
  - alias: hasp_bedroom_plate_00_AutomationGroupUpdate
    trigger:
    - platform: homeassistant
      event: start
    action:
    - service: group.set
      data_template:
        object_id: "bedroom_plate_automations"
        entities: >-
          {%- for item in states.automation if ((item.entity_id | lower).startswith('automation.hasp_bedroom_plate_')) -%}
          {{ item.entity_id }}
          {% if not loop.last %}, {% endif %}
          {%- endfor -%}
