##############################################################################
# Automations to set colors on HASP Page 3
#
# WARNING: These automations can quadruple MQTT traffic on Home Assistant or
# HASP restart.  It's recommended that you selectively enable these on a per-
# page basis to avoid flooding your MQTT broker with traffic.
#
# The default page3 automations already set button colors in response to
# toggled state, rendering additional color change automations unnecessary.
# These are included here and commented out in case you want to use page 3
# for other purposes than the included automation.

# automation:
#   - alias: hasp_bedroom_plate_p3_ColorConfig
#     trigger:
#     - platform: state
#       entity_id: 'binary_sensor.bedroom_plate_connected'
#       to: 'on'
#     - platform: homeassistant
#       event: start
#     - platform: state
#       entity_id: input_number.hasp_bedroom_plate_selectedbackgroundcolor
#     - platform: state
#       entity_id: input_number.hasp_bedroom_plate_unselectedbackgroundcolor
#     - platform: state
#       entity_id: input_number.hasp_bedroom_plate_selectedforegroundcolor
#     - platform: state
#       entity_id: input_number.hasp_bedroom_plate_unselectedforegroundcolor
#     action:
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[4].pco'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_selectedforegroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[4].bco'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_selectedbackgroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[4].pco2'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_unselectedforegroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[4].bco2'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_unselectedbackgroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[5].pco'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_selectedforegroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[5].bco'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_selectedbackgroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[5].pco2'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_unselectedforegroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[5].bco2'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_unselectedbackgroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[6].pco'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_selectedforegroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[6].bco'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_selectedbackgroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[6].pco2'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_unselectedforegroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[6].bco2'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_unselectedbackgroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[7].pco'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_selectedforegroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[7].bco'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_selectedbackgroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[7].pco2'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_unselectedforegroundcolor.state|int }}'
#     - service: mqtt.publish
#       data:
#         topic: 'hasp/bedroom_plate/command/p[3].b[7].bco2'
#         payload_template: '{{ states.input_number.hasp_bedroom_plate_unselectedbackgroundcolor.state|int }}'
