##############################################################################
# Automations to display the weather forecast and current temp on page 2

automation:
  # Display weather details on page 2 when weather updates or on HASP init
  - alias: hasp_bedroom_plate_p2_Weather
    trigger:
    - platform: state
      entity_id: weather.metno
    - platform: state
      entity_id: 'binary_sensor.bedroom_plate_connected'
    - platform: homeassistant
      event: start
    condition:
    - condition: state
      entity_id: 'binary_sensor.bedroom_plate_connected'
      state: 'on'
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom_plate/command/p[2].b[6].font'
        payload: '3'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom_plate/command/p[2].b[6].txt'
        payload_template: '"{{state_attr("weather.metno","temperature")|int}}F"'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom_plate/command/p[2].b[7].font'
        payload_template: '{% if states.weather.metno.state|length <= 6 -%}3{% elif (states.weather.metno.state|length > 6) and (states.weather.metno.state|length <= 10) %}2{% elif (states.weather.metno.state|length > 10) and (states.weather.metno.state|length <= 15) %}1{% else %}0{%- endif %}'
    - service: mqtt.publish
      data:
        topic: 'hasp/bedroom_plate/command/p[2].b[7].txt'
        payload_template: '"{{states.weather.metno.state|wordwrap(20, wrapstring="\\r")|title}}"'
