alarm_control_panel:
  - platform: arlo
    away_mode_name: Armed

arlo:
  username: !secret arlo_username
  password: !secret arlo_password

camera:
  - platform: arlo

sensor:
  - platform: arlo

automation:
  - id: arlo_on_with_alarm
    alias: Turn Arlo on with the alarm
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_panel
        to: armed_home
      - platform: state
        entity_id: alarm_control_panel.alarm_panel
        to: armed_away
    action:
      service: alarm_control_panel.alarm_arm_home
      entity_id: alarm_control_panel.hercules

  - id: arlo_off_with_alarm
    alias: Turn Arlo off with the alarm
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_panel
        to: disarmed
    action:
      service: alarm_control_panel.alarm_disarm
      entity_id: alarm_control_panel.hercules

