automation:
  - id: baby_lights_sync_off
    alias: Turn off the T-Rex Light with the BabyCam
    trigger:
      - platform: state
        entity_id: light.aarlo_babycam
        to: 'off'
    action:
      service: light.turn_off
      entity_id: light.t_rex

  - id: baby_lights_sync_on
    alias: Turn on the T-Rex Light with the BabyCam
    trigger:
      - platform: state
        entity_id: light.aarlo_babycam
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.t_rex
