climate:
  - platform: generic_thermostat
    name: Baby Room Heater
    heater: switch.baby_room_heat
    target_sensor: sensor.aarlo_temperature_babycam

automation:
  - id: baby_heat_sync_off
    alias: Turn off the Baby Heater with the BabyCam
    trigger:
      - platform: state
        entity_id: light.aarlo_babycam
        to: "off"
    action:
      service: climate.set_hvac_mode
      data:
        entity_id: climate.baby_room_heater
        hvac_mode: "off"

  - id: baby_heat_sync_on
    alias: Turn on the Baby Heater with the BabyCam
    trigger:
      - platform: state
        entity_id: light.aarlo_babycam
        to: "on"
    action:
      service: climate.set_hvac_mode
      data:
        entity_id: climate.baby_room_heater
        hvac_mode: heat

  - id: baby_lights_sync_off
    alias: Turn off the T-Rex Light with the BabyCam
    trigger:
      - platform: state
        entity_id: light.aarlo_babycam
        to: 'off'
    action:
      service: light.turn_off
      entity_id: light.t_rex

  - id: baby_lights_sync_on
    alias: Turn on the T-Rex Light with the BabyCam
    trigger:
      - platform: state
        entity_id: light.aarlo_babycam
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.t_rex

  - id: babycam_color_on
    alias: Turn on the BabyCam light red when turned on
    trigger:
      - platform: state
        entity_id: light.aarlo_babycam
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.aarlo_babycam
      data:
        color_name: red

  - id: babycam_wakeup_color
    alias: Turn on the BabyCam light green at 6am
    trigger:
      - platform: time
        at: !secret constants_wake_time
    condition:
      - condition: state
        entity_id: light.aarlo_babycam
        state: 'on'
    action:
      service: light.turn_on
      entity_id: light.aarlo_babycam
      data:
        color_name: green
