group:
  bedroom_alarm:
    name: Bedroom Alarm
    entities:
      - input_datetime.bedroom_alarm_clock_time
      - automation.bedroom_alarm_weekdays

input_datetime:
  bedroom_alarm_clock_time:
    name: Alarm Time
    has_date: false
    has_time: true
    initial: '06:45'

automation:
  - id: bedroom_alarm
    alias: "Bedroom Alarm (weekdays)"
    trigger:
      platform: template
      value_template: "{{ states('sensor.time') == (states.input_datetime.bedroom_alarm_clock_time.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      service: script.bedroom_wake_up

script:
  bedroom_wake_up:
    alias: Bedroom Wake-Up
    sequence:
    - data:
        brightness: 1
        color_temp: 454
        entity_id:
          - light.lesleys_reading_lamp
          - light.matts_reading_lamp
      service: light.turn_on

    - delay: 00:03:45
    - data:
        brightness: 50
        color_temp: 400
        entity_id:
          - light.lesleys_reading_lamp
          - light.matts_reading_lamp
      service: light.turn_on

    - delay: 00:03:45
    - data:
        brightness: 100
        color_temp: 350
        entity_id:
          - light.lesleys_reading_lamp
          - light.matts_reading_lamp
      service: light.turn_on

    - delay: 00:03:45
    - data:
        brightness: 150
        color_temp: 300
        entity_id:
          - light.lesleys_reading_lamp
          - light.matts_reading_lamp
      service: light.turn_on

    - delay: 00:03:45
    - data:
        brightness: 254
        color_temp: 250
        entity_id:
          - light.lesleys_reading_lamp
          - light.matts_reading_lamp
      service: light.turn_on
