sensor:
  - platform: mqtt
    state_topic: "tele/bedroom-fan/SENSOR"
    name: "Bedroom Humidity"
    unit_of_measurement: "%"
    value_template: '{{ value_json.AM2301.Humidity }}'

  - platform: mqtt
    state_topic: "tele/bedroom-fan/SENSOR"
    name: "Bedroom Temperature"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.AM2301.Temperature }}'
