group:
  radarr:
    name: Radarr
    icon: mdi:movie
    entities:
      - sensor.radarr_movies
      - sensor.radarr_upcoming
      - sensor.radarr_commands
      - sensor.radarr_disk_space
      - sensor.radarr_status

  sonarr:
    name: Sonarr
    icon: mdi:television-classic
    entities:
      - sensor.sonarr_series
      - sensor.sonarr_upcoming
      - sensor.sonarr_wanted
      - sensor.sonarr_queue
      - sensor.sonarr_commands
      - sensor.sonarr_disk_space

sensor:
  - platform: radarr
    host: !secret radarr_host
    api_key: !secret radarr_api_key
    monitored_conditions:
      - movies
      - upcoming
      - commands
      - diskspace
      - status

  - platform: sonarr
    host: !secret sonarr_host
    api_key: !secret sonarr_api_key
    monitored_conditions:
      - series
      - upcoming
      - wanted
      - queue
      - commands
      - diskspace
