binary_sensor:
  - platform: mqtt
    name: "Garage Door Open"
    state_topic: "tele/garage-door/open"
    payload_on: "1"
    payload_off: "0"
    device_class: garage_door

  - platform: mqtt
    name: "Garage Door Closed"
    state_topic: "tele/garage-door/closed"
    payload_on: "1"
    payload_off: "0"
    device_class: garage_door

homeassistant:
  customize:
    binary_sensor.garage_door_open:
      hidden: true
    binary_sensor.garage_door_closed:
      hidden: true
    light.garage_door_light:
      assumed_state: false

group:
  garage:
    name: Garage
    icon: mdi:garage
    entities:
      - sensor.garage_door
      - binary_sensor.garage_door_open
      - binary_sensor.garage_door_closed
      - light.garage_door_light
      - script.toggle_garage_door

script:
  toggle_garage_door:
    alias: Open/Close Garage Door
    sequence:
      - service: mqtt.publish
        data_template:
          topic: garage-door/cmnd/POWER1
          payload: "ON"

sensor:
  - platform: template
    sensors:
      garage_door:
        friendly_name: "Garage Door"
        icon_template: >-
          {% if is_state('binary_sensor.garage_door_closed', 'on') and is_state('binary_sensor.garage_door_open', 'off') %}
            mdi:garage
          {% elif is_state('binary_sensor.garage_door_closed', 'off') and is_state('binary_sensor.garage_door_open', 'on') %}
            mdi:garage-open
          {% elif is_state('binary_sensor.garage_door_closed', 'off') and is_state('binary_sensor.garage_door_open', 'off') %}
            mdi:garage-alert
          {% else %}
            mdi:alert
          {% endif %}
        value_template: >-
          {% if is_state('binary_sensor.garage_door_closed', 'on') and is_state('binary_sensor.garage_door_open', 'off') %}
            Closed
          {% elif is_state('binary_sensor.garage_door_closed', 'off') and is_state('binary_sensor.garage_door_open', 'on') %}
            Open
          {% elif is_state('binary_sensor.garage_door_closed', 'off') and is_state('binary_sensor.garage_door_open', 'off') %}
            Partial
          {% else %}
            Unknown
          {% endif %}

light:
  - platform: mqtt
    schema: template
    name: "Garage Door Light"
    assumed_state: false
    command_off_template: "ON"
    command_on_template: "ON"
    command_topic: "garage-door/cmnd/POWER2"
    optimistic: true
    state_template: "{% if (value | int) >= 18 -%}on{% else %}off{%- endif %}"
    state_topic: "tele/garage/LIGHT"
