sensor:
  #https://home-assistant.io/components/sensor.systemmonitor/
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
      - type: last_boot
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: load_1m
      - type: load_5m
      - type: load_15m

  #https://www.home-assistant.io/components/sensor.command_line/
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ (float(value) * 0.001) | round(1) }}'
