automation:
  - id: hot_tub_lights_off
    alias: Turn off Hot Tub Lights with Rock Lamp
    trigger:
      - platform: state
        entity_id: light.rock_lamp
        to: 'off'
    action:
      service: light.turn_off
      entity_id: light.hot_tub_lights

  - id: hot_tub_lights_on
    alias: Turn on Hot Tub Lights with Rock Lamp
    trigger:
      - platform: state
        entity_id: light.rock_lamp
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.hot_tub_lights

sensor:
  - platform: mqtt
    state_topic: "tele/hot-tub/SENSOR"
    name: "Hot Tub"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.DS18B20.Temperature }}'
