group:
  ice_pack:
    name: Ice Pack
    icon: mdi:garage
    entities:
      - switch.ice_pack_2
      - automation.ice_pack_off_after_20_minutes_of_being_on
      - automation.ice_pack_on_after_40_minutes_of_being_off

automation:
  - id: ice_pack_off_after_20_minutes_of_being_on
    alias: Ice Pack off after 20 minutes of being on
    trigger:
      - platform: state
        entity_id: switch.ice_pack_2
        to: 'on'
        for:
          minutes: 20
    action:
      - service: switch.turn_off
        data:
          entity_id:
            - switch.ice_pack_2

  - id: ice_pack_on_after_40_minutes_of_being_off
    alias: Ice Pack on after 40 minutes of being off
    trigger:
      - platform: state
        entity_id: switch.ice_pack_2
        to: 'off'
        for:
          minutes: 40
    action:
        - service: switch.turn_on
          data:
            entity_id:
              - switch.ice_pack_2
