ios:
  push:
    categories:
      - name: Arrive Home
        identifier: 'arrive_home'
        actions:
          - identifier: 'OPEN_GARAGE'
            title: 'Open Garage'
            authenticationRequired: yes

automation:
  - id: matt_arrives_home_iphone
    alias: Notify Matt's phone when he arrives home
    trigger:
      - platform: state
        entity_id: device_tracker.matthews_iphone
        to: home
    action:
      - service: notify.ios_matthews_iphone
        data:
          message: "Matt Arrived Home"
          data:
            push:
              category: "arrive_home"
  - id: lesley_arrives_home_iphone
    alias: Notify Lesley's phone when she arrives home
    trigger:
      - platform: state
        entity_id: device_tracker.lesley_paiges_iphone
        to: home
    action:
      - service: notify.ios_lesley_paiges_iphone
        data:
          message: "Lesley Arrived Home"
          data:
            push:
              category: "arrive_home"
  - id: iphone_open_garage_door
    alias: iPhone Open Garage Door
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: OPEN_GARAGE
    action:
      - service: script.toggle_garage_door
