group:
  smoke_and_co_detectors:
    name: Smoke and CO Detectors
    icon: mdi:smoke-detector
    entities:
      - zwave.kitchen_smoke_and_co_detector
      - sensor.kitchen_smoke_and_co_detector_alarm_level
      - sensor.kitchen_smoke_and_co_detector_alarm_type
      - sensor.kitchen_smoke_and_co_detector_battery_level
      - zwave.upstairs_smoke_and_co_detector
      - sensor.upstairs_smoke_and_co_detector_alarm_level
      - sensor.upstairs_smoke_and_co_detector_alarm_type
      - sensor.upstairs_smoke_and_co_detector_battery_level

sensor:
  - platform: template
    sensors:
      kitchen_smoke_and_co_detector_battery_level:
        value_template: '{{states.zwave.kitchen_smoke_and_co_detector.attributes.battery_level}}'
        friendly_name: 'Kitchen Smoke/CO Alarm Battery'
        unit_of_measurement: '%'
      upstairs_smoke_and_co_detector_battery_level:
        value_template: '{{states.zwave.upstairs_smoke_and_co_detector.attributes.battery_level}}'
        friendly_name: 'Upstairs Smoke/CO Alarm Battery'
        unit_of_measurement: '%'
