sensor:
  - platform: template
    sensors:
      kitchen_smoke_and_co_detector_battery_level:
        value_template: "{{states.zwave.kitchen_smoke_and_co_detector.attributes.battery_level}}"
        friendly_name: "Kitchen Smoke/CO Alarm Battery"
        unit_of_measurement: "%"
      upstairs_smoke_and_co_detector_battery_level:
        value_template: "{{states.zwave.upstairs_smoke_and_co_detector.attributes.battery_level}}"
        friendly_name: "Upstairs Smoke/CO Alarm Battery"
        unit_of_measurement: "%"
