automation:
  - id: sonoff_state_on_ha-start_up
    alias: "Sonoff state on HA start-up"
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: mqtt.publish
        data:
          topic: "cmnd/sonoffs/SetOption19"
          payload: "1"
      - service: mqtt.publish
        data:
          topic: "cmnd/sonoffs/backlog"
          payload: "power1 ;power2 ;power3 ;power4 ;power5"
      - service: mqtt.publish
        data:
          topic: "cmnd/sonoffs/state"
          payload: ""
