group:
  weather:
    name: Weather
    icon: mdi:weather-cloudy
    entities:
      - sensor.dark_sky_overnight_low_apparent_temperature_0
      - sensor.dark_sky_temperature
      - sensor.dark_sky_daytime_high_apparent_temperature_0
      # - sensor.dark_sky_icon
      # - sensor.dark_sky_icon_0
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0
      # - sensor.dark_sky_temperature_0

sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - temperature
      - apparent_temperature_high
      - apparent_temperature_low
