automation:
  - id: alarm_triggered
    alias: Notify phones when alarm is triggered
    trigger:
      - platform: state
        entity_id: alarm_control_panel.alarm_panel
        to: triggered
    action:
      - service: notify.all_iphones
        data:
          message: "Alarm Triggered"
          data:
            push:
              category: "alarm_triggered"

  - id: iphone_disarm_alarm
    alias: iPhone Disarm Alarm
    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: DISARM
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          code: !secret alarm_master_code
          entity_id: alarm_control_panel.alarm_panel

ios:
  push:
    categories:
      - name: Alarm Triggered
        identifier: 'alarm_triggered'
        actions:
          - identifier: 'DISARM'
            title: 'Disarm'
            destructive: yes
            authenticationRequired: yes

